services:
  db:
    container_name: calendario_db
    image: postgres:16
    environment:
      POSTGRES_DB: cenart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cenart"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    container_name: calendario_pgadmin
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: david0023axc178@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

  api:
    container_name: calendario_api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/cenart
      CORS_ORIGIN: "http://127.0.0.1:5500"
      NODE_ENV: development

      # ⬇️⬇️ NUEVO: configuración para MongoDB Atlas
      MONGO_URI: "mongodb+srv://davidUser:david123@daviixc1.zurhsrw.mongodb.net/?appName=Daviixc1"
      MONGO_DB_NAME: "ceart_metrics"
    ports:
      - "3333:3000"
    volumes:
      - ./api/src:/app/src
      - ./api/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata:
  pgadmindata:


